public  class ogrenci11 {
    public ogrenci11(){
        system.debug('yeni bir kayit yapildi');

    }

    public String firstName;
    public String lastName;
    private String schoolName='Dream School';
    public String className;
    public String language;
    public boolean art;
    public boolean sport;
    public integer engGrade;
    public integer matGrade;
    public integer fenGrade;

}
