public  class primitiveDataTypeDemo5 {
    public void printNewDateTime(){
        //year,month,day,hour,minute.second

        /* datetime dt3=datetime.newInstance(2022,10,9,10,10,10);
        system.debug('dt3 is -> '+ dt3); 

        Datetime dt4=Datetime.newInstance(0);
        system.debug('dt4 is-> ' + dt4);

        Long longtime=46325465L;
        Datetime dt4=Datetime.newInstance(longtime);
        system.debug('dt4 is-> ' + dt4);

        Datetime dt6=datetime.now();
        system.debug('dt6 is ' + dt6); 

        Datetime dt5=datetime.newInstanceGMT(2022,1,28,18,2,3);
        system.debug('dt5 is-> ' + dt5); */

        


    }
}
