public  class SalesforceDeveloper {
    public void myFirstCode(){
        system.debug('My favorite city is New York');
        system.debug('My favorite movie is Interstellar');
        system.debug('My favorite season is winter');
        String myCity='Bursa';
        integer faveNum=26;
        system.debug(faveNum);
        system.debug(myCity);
        system.debug('Favori Numaram-> '+faveNum+' ve Favori Şehrim '+myCity);
    } 
    
}
