public  class switch2 {

    public String returnNum(String x){
        String result='';

        switch on x {
            when 'Harry Potter' {
                result='The Boy Who Lived';
                }
            when 'Sirious Black'{
                result='Prisoner of Azkaban';
            }
            when 'Albus Dumbledor' {
                result='Headmaster';
            }
            when 'Severus Snape'{
                result='ALWAYS';
            }
        }
        return result;

    }
    
}
