public  class Loops_assignment {
     
     public void Forloop(integer n){
          for (Integer i = 0; i < n; i++){
               System.debug(i);

          }
         
          }

          public void printEven(integer x,Integer y){
               for(integer i=1;i<100;i++){
                    Integer remainder=math.mod(i, 2);
                    if(remainder==0){
                         System.debug(i);
                    }

                    }

               }
               
          } 
          
    

