Car tesla= new Car();
tesla.switchOn();
tesla.carColor='Black';
system.debug('tesla-> ' + tesla); 
tesla.carName='Model S';
tesla.drive();
tesla.driveAtMaxSpeed();



car bmw= new car();
 bmw.carColor='white';
bmw.switchOn();
System.debug('Bmw car color-> ' + bmw.carColor);
bmw.carName='xyz';
bmw.drive();
bmw.driveAtMaxSpeed();

car toyota=new car();
toyota.carColor='Blue';
toyota.switchOn();
toyota.carName='Toyota';
toyota.drive();
toyota.driveAtMaxSpeed();

