
public  class SPTriggerHandlerTestAss {

    /*@isTest
    private static void createDefaultTicketTest() {
       
        SalesforceProjectTriggerHandler.createDefaultTicket(); 
        
        List<Salesforce_Ticket__c> testList=new List<Salesforce_Ticket__c>();

        for (salesforce_project__c eachSP :spTriggerNew ) {
            eachSP.Subject__c='Default Ticket';
            eachSP.salesforce_project__c=eachSP.id;
            testList.add(eachSP);
        }
        insert testList; */

        
        
    }

    

